# Generated by Django 4.2.2 on 2023-07-12 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.gcloud


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type_room', models.CharField(choices=[('STANDARD', 'standard'), ('JUNIOR SUITE', 'junior suite'), ('SUITE', 'suite')], default='STANDARD', max_length=255)),
                ('number_rooms', models.CharField(choices=[('ONE ROOM', 'one room'), ('TWO ROOM', 'two room'), ('THREE ROOM', 'three room'), ('FOUR ROOM', 'four room')], default='ONE ROOM', max_length=100)),
                ('number_beds', models.CharField(choices=[('SINGLE-BED', 'single-bed'), ('DOUBLE-BED', 'double-bed'), ('TRIPLE-BED', 'triple-bed'), ('FOUR-BED', 'four-bed'), ('FIVE-BED', 'five-bed'), ('SIX-BED', 'six-bed'), ('EIGHT-BED', 'eight-bed')], default='SINGLE-BED', max_length=100)),
                ('night_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='accommodation_images')),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='destination_images')),
                ('url_map_destination', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ('-value',),
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='stay_images')),
                ('url_map_stay', models.URLField(blank=True, max_length=255)),
                ('amenities', models.ManyToManyField(blank=True, to='TravelMore.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='TravelMore.destination')),
            ],
        ),
        migrations.CreateModel(
            name='StayFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='stay_frames_images')),
                ('stays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_frames', to='TravelMore.stay')),
            ],
            options={
                'verbose_name': 'Stay frame',
                'verbose_name_plural': 'Stay frames',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ReviewStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_stays', to='TravelMore.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_stay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_destinations', to='TravelMore.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_destination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_rating_stay', to='TravelMore.ratingstar')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_rating', to='TravelMore.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_stay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rating', to='TravelMore.destination')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_rating_destination', to='TravelMore.ratingstar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_destination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('number_of_guests', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='TravelMore.accommodation')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_stay', to='TravelMore.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='accommodation_frames_images')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_frames', to='TravelMore.accommodation')),
            ],
            options={
                'verbose_name': 'Accommodation frame',
                'verbose_name_plural': 'Accommodation frames',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='TravelMore.amenity'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='TravelMore.stay'),
        ),
    ]
