# Generated by Django 4.2.2 on 2023-06-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('review_number', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
                ('amenities', models.CharField(blank=True, choices=[('wifi', 'Wi-Fi'), ('parking', 'Parking'), ('pool', 'Swimming Pool'), ('balcony', 'Balcony'), ('restaurant', 'Restaurant')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('number_of_guests', models.IntegerField()),
                ('night_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelMore.stay')),
            ],
        ),
    ]
