# Generated by Django 4.2.2 on 2023-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accommodationframes",
            options={
                "ordering": ("title",),
                "verbose_name": "Accommodation frame",
                "verbose_name_plural": "Accommodation frames",
            },
        ),
        migrations.AddField(
            model_name="accommodation",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="TravelMore.amenity"),
        ),
    ]
