# Generated by Django 4.2.2 on 2023-06-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0002_alter_accommodationframes_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="TravelMore.stay",
            ),
        ),
    ]
