# Generated by Django 4.2.2 on 2023-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0003_accommodation_stay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="night_price",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="night_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
