# Generated by Django 4.2.2 on 2023-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0004_remove_booking_night_price_accommodation_night_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
