# Generated by Django 4.2.2 on 2023-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0005_accommodation_is_booked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="rooms",
        ),
        migrations.AddField(
            model_name="booking",
            name="rooms",
            field=models.ManyToManyField(
                related_name="booking_rooms", to="TravelMore.accommodation"
            ),
        ),
    ]
