# Generated by Django 4.2.2 on 2023-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0006_remove_booking_rooms_booking_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="rooms",
            field=models.ManyToManyField(
                related_name="bookings", to="TravelMore.accommodation"
            ),
        ),
    ]
