# Generated by Django 4.2.2 on 2023-06-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0007_alter_booking_rooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="is_booked",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="rooms",
        ),
        migrations.AddField(
            model_name="booking",
            name="rooms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_room",
                to="TravelMore.accommodation",
            ),
        ),
    ]
