# Generated by Django 4.2.2 on 2023-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "TravelMore",
            "0008_remove_accommodation_is_booked_remove_booking_rooms_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
