# Generated by Django 4.2.2 on 2023-06-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0009_accommodation_is_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodations",
                to="TravelMore.stay",
            ),
        ),
    ]
