# Generated by Django 4.2.2 on 2023-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TravelMore", "0010_alter_accommodation_stay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
