# Generated by Django 4.2.2 on 2023-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_blacklistedtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlacklistedToken",
        ),
    ]
