# Generated by Django 4.2.2 on 2023-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_delete_blacklistedtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="residency",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
